name: Test Rust Application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Dependencies
        run: sudo apt-get install -y wget

      - name: Create Downloads Directory
        run: |
          mkdir -p ./Downloads
          echo "Created Downloads directory at $(pwd)/Downloads"

      - name: Build Application (downloadManager)
        run: |
          cargo build --release --bin downloadManager
          echo "Application (downloadManager) built successfully."

      - name: Run Application in Background
        run: |
          target/release/downloadManager > app.log 2>&1 &
          echo "Application started in background."

      - name: Download Test Files
        run: |
          wget -P ./Downloads https://via.placeholder.com/150 -O ./Downloads/test_image1.jpg
          wget -P ./Downloads https://via.placeholder.com/200 -O ./Downloads/test_image2.jpg
          wget -P ./Downloads https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf -O ./Downloads/sample.pdf
          echo "Test files downloaded and created."

      - name: Verify Files Moved
        run: |
          if [ ! -f ./Downloads/Images/test_image1.jpg ]; then
            echo "Test image1 was not moved to Images directory!" && exit 1
          fi
          if [ ! -f ./Downloads/Images/test_image2.jpg ]; then
            echo "Test image2 was not moved to Images directory!" && exit 1
          fi
          if [ ! -f ./Downloads/Documents/sample.pdf ]; then
            echo "Sample PDF was not moved to Documents directory!" && exit 1
          fi
          echo "Files moved successfully!"

      - name: Stop Background Application
        run: |
          pkill -f 'target/release/downloadManager'
          echo "Background application stopped."

      - name: Verify Weekly Report Generation
        run: |
          if [ ! -f ./Downloads/Weekly_Report.html ]; then
            echo "Weekly report was not generated!" && exit 1
          fi
          echo "Weekly report generated successfully!"

      - name: Display Application Logs
        run: |
          echo "Displaying application logs:" && cat app.log
